import * as tl from 'azure-pipelines-task-lib/task';
import * as path from 'path';
import * as fs from 'fs';
import * as child_process from 'child_process';
import * as os from 'os';
import * as https from 'https';

/**
 * Check if PowerShell 7 (pwsh) is available on the system
 */
function checkPwshAvailable(): boolean {
    try {
        const result = child_process.spawnSync('pwsh', ['--version'], {
            encoding: 'utf8',
            shell: true
        });
        return result.status === 0;
    } catch {
        return false;
    }
}

/**
 * Check if we're running on Windows
 */
function isWindows(): boolean {
    return process.platform === 'win32';
}

function normalizeInput(value: string | undefined): string | undefined {
    if (!value) {
        return undefined;
    }

    const trimmed = value.trim();
    if (!trimmed || /^\$\([^)]+\)$/.test(trimmed)) {
        return undefined;
    }

    return trimmed;
}

function extractChangedFilePath(changedFile: string): string {
    const bracketIndex = changedFile.lastIndexOf(' [');
    if (bracketIndex <= 0) {
        return changedFile.trim();
    }

    return changedFile.slice(0, bracketIndex).trim();
}

function filterXmlChangedFiles(changedFiles: string[]): string[] {
    return changedFiles.filter(file => {
        const filePath = extractChangedFilePath(file);
        return filePath.toLowerCase().endsWith('.xml');
    });
}

function escapeHtml(value: string): string {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

function extractReviewFindings(copilotOutput: string): string {
    const normalizedOutput = (copilotOutput || '').replace(/\r\n/g, '\n').trim();
    if (!normalizedOutput) {
        return 'No output generated by Copilot.';
    }

    const headingMatch = normalizedOutput.match(/^##\s*Code Review\s*[—-]\s*Findings\b/im);
    if (!headingMatch || headingMatch.index === undefined) {
        return normalizedOutput;
    }

    return normalizedOutput.slice(headingMatch.index).trim();
}

function hasBlockingFindings(copilotOutput: string): boolean {
    const normalized = copilotOutput.toLowerCase();

    const explicitAcceptedPatterns = [
        /\*\*result:\s*✅\s*accepted\*\*/i,
        /result:\s*accepted/i,
        /\*\*accepted\.?\*\*/i,
        /\baccepted\.?\b/i
    ];

    const explicitRejectedPatterns = [
        /\*\*result:\s*❌\s*rejected\*\*/i,
        /result:\s*rejected/i,
        /\*\*rejected\.?\*\*/i,
        /\brejected\.?\b/i
    ];

    if (explicitRejectedPatterns.some(pattern => pattern.test(copilotOutput))) {
        return true;
    }

    if (explicitAcceptedPatterns.some(pattern => pattern.test(copilotOutput))) {
        return false;
    }

    if (normalized.includes('no blocking issues found')) {
        return false;
    }

    return true;
}

function getReviewReferences(): string[] {
    const sourceVersion = normalizeInput(tl.getVariable('Build.SourceVersion'));
    const sourceVersionMessage = normalizeInput(tl.getVariable('Build.SourceVersionMessage'));
    const sourceBranch = normalizeInput(tl.getVariable('Build.SourceBranch'));
    const repository = normalizeInput(tl.getVariable('Build.Repository.Name'));
    const buildId = normalizeInput(tl.getVariable('Build.BuildId'));
    const buildNumber = normalizeInput(tl.getVariable('Build.BuildNumber'));

    const refs: string[] = [];
    if (repository) {
        refs.push(`Repository: ${repository}`);
    }
    if (sourceBranch) {
        refs.push(`Branch: ${sourceBranch}`);
    }
    if (sourceVersion) {
        refs.push(`SourceVersion (CS/Commit): ${sourceVersion}`);
    }
    if (sourceVersionMessage) {
        refs.push(`SourceVersionMessage: ${sourceVersionMessage}`);
    }
    if (buildId) {
        refs.push(`BuildId: ${buildId}`);
    }
    if (buildNumber) {
        refs.push(`BuildNumber: ${buildNumber}`);
    }

    return refs;
}

function parseTfvcChangesetId(value: string | undefined): string | undefined {
    const normalized = normalizeInput(value);
    if (!normalized) {
        return undefined;
    }

    const exactMatch = normalized.match(/^C?(\d+)$/i);
    if (exactMatch?.[1]) {
        return exactMatch[1];
    }

    const prefixedMatch = normalized.match(/\bC(\d+)\b/i);
    if (prefixedMatch?.[1]) {
        return prefixedMatch[1];
    }

    const changesetWordMatch = normalized.match(/\bchangeset\s*#?\s*(\d+)\b/i);
    if (changesetWordMatch?.[1]) {
        return changesetWordMatch[1];
    }

    return undefined;
}

function resolveTfvcChangesetId(): string | undefined {
    const candidates = [
        normalizeInput(tl.getVariable('Build.SourceVersion')),
        normalizeInput(tl.getVariable('Build.SourceVersionMessage')),
        normalizeInput(tl.getVariable('Build.SourceTfvcShelveset'))
    ];

    for (const candidate of candidates) {
        const parsed = parseTfvcChangesetId(candidate);
        if (parsed) {
            return parsed;
        }
    }

    return undefined;
}

function resolveTfvcShelveset(): string | undefined {
    return normalizeInput(tl.getVariable('Build.SourceTfvcShelveset'));
}

function unwrapShelvesetResponse(response: any): any {
    if (!response) {
        return undefined;
    }

    if (Array.isArray(response?.value) && response.value.length > 0) {
        return response.value[0];
    }

    return response;
}

function truncateForTitle(value: string, maxLength: number = 200): string {
    const sanitized = value
        .replace(/\*{3}NO_CI\*{3}/gi, '')
        .replace(/\s+/g, ' ')
        .trim();
    if (sanitized.length <= maxLength) {
        return sanitized;
    }

    return `${sanitized.slice(0, Math.max(0, maxLength - 3)).trim()}...`;
}

async function invokeAzureDevOpsApiWithFallback(
    endpointCandidates: string[],
    token: string,
    authType: string,
    notFoundMessage: string
): Promise<any> {
    let response: any;
    let lastError: unknown;

    for (const endpoint of endpointCandidates) {
        try {
            response = await invokeAzureDevOpsApi(endpoint, token, authType);
            break;
        } catch (error) {
            lastError = error;
            const errorMessage = error instanceof Error ? error.message : String(error);
            if (!errorMessage.includes('(404)')) {
                throw error;
            }
        }
    }

    if (!response) {
        throw lastError instanceof Error
            ? lastError
            : new Error(notFoundMessage);
    }

    return response;
}

async function getTfvcChangesetDetails(
    collectionUri: string,
    project: string,
    changesetId: string,
    token: string,
    authType: string
): Promise<any> {
    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/changesets/${changesetId}?api-version=7.1`
            : undefined,
        `${collectionUri}/_apis/tfvc/changesets/${changesetId}?api-version=7.1`
    ].filter((value: string | undefined): value is string => !!value);

    return invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch TFVC changeset ${changesetId}.`
    );
}

async function getTfvcChangesetLinkedWorkItemIds(
    collectionUri: string,
    project: string,
    changesetId: string,
    token: string,
    authType: string
): Promise<number[]> {
    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/changesets/${changesetId}/workItems?api-version=7.1`
            : undefined,
        `${collectionUri}/_apis/tfvc/changesets/${changesetId}/workItems?api-version=7.1`
    ].filter((value: string | undefined): value is string => !!value);

    const response = await invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch linked work items for TFVC changeset ${changesetId}.`
    );

    const workItems = Array.isArray(response?.value) ? response.value : [];
    return workItems
        .map((item: any) => Number(item?.id))
        .filter((id: number) => Number.isFinite(id));
}

async function getTfvcShelvesetDetails(
    collectionUri: string,
    project: string,
    shelveset: string,
    token: string,
    authType: string
): Promise<any> {
    const encodedShelveset = encodeURIComponent(shelveset);
    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/shelvesets/${encodedShelveset}?api-version=7.1`
            : undefined,
        `${collectionUri}/_apis/tfvc/shelvesets/${encodedShelveset}?api-version=7.1`
    ].filter((value: string | undefined): value is string => !!value);

    const response = await invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch TFVC shelveset ${shelveset}.`
    );

    return unwrapShelvesetResponse(response);
}

async function getTfvcShelvesetLinkedWorkItemIds(
    collectionUri: string,
    project: string,
    shelveset: string,
    token: string,
    authType: string
): Promise<number[]> {
    const encodedShelveset = encodeURIComponent(shelveset);
    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/shelvesets/${encodedShelveset}/workItems?api-version=7.1`
            : undefined,
        `${collectionUri}/_apis/tfvc/shelvesets/${encodedShelveset}/workItems?api-version=7.1`,
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/shelvesets/${encodedShelveset}/workitems?api-version=7.1`
            : undefined,
        `${collectionUri}/_apis/tfvc/shelvesets/${encodedShelveset}/workitems?api-version=7.1`
    ].filter((value: string | undefined): value is string => !!value);

    const response = await invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch linked work items for TFVC shelveset ${shelveset}.`
    );

    const workItems = Array.isArray(response?.value) ? response.value : [];
    return workItems
        .map((item: any) => Number(item?.id))
        .filter((id: number) => Number.isFinite(id));
}

async function isTaskWorkItem(
    collectionUri: string,
    project: string,
    workItemId: number,
    token: string,
    authType: string
): Promise<boolean> {
    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/wit/workitems/${workItemId}?fields=System.WorkItemType&api-version=7.1`
            : undefined,
        `${collectionUri}/_apis/wit/workitems/${workItemId}?fields=System.WorkItemType&api-version=7.1`
    ].filter((value: string | undefined): value is string => !!value);

    const response = await invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch work item ${workItemId}.`
    );

    const workItemType = String(response?.fields?.['System.WorkItemType'] || '').trim().toLowerCase();
    const rawWorkItemType = response?.fields?.['System.WorkItemType'] || '(empty)';
    tl.warning(`[ParentResolution] Work item ${workItemId} type raw: "${rawWorkItemType}" -> normalized: "${workItemType}"`);
    return workItemType === 'task' || workItemType.includes('attivit');
}

async function resolveParentTaskIdFromChangeset(
    collectionUri: string,
    project: string,
    changesetId: string,
    token: string,
    authType: string
): Promise<number | undefined> {
    tl.warning(`[ParentResolution] Querying work items linked to changeset ${changesetId}...`);
    const linkedWorkItemIds = await getTfvcChangesetLinkedWorkItemIds(
        collectionUri,
        project,
        changesetId,
        token,
        authType
    );

    tl.warning(`[ParentResolution] Changeset ${changesetId} has ${linkedWorkItemIds.length} linked work item(s): [${linkedWorkItemIds.join(', ')}]`);

    for (const workItemId of linkedWorkItemIds) {
        try {
            const isTask = await isTaskWorkItem(collectionUri, project, workItemId, token, authType);
            tl.warning(`[ParentResolution] Work item ${workItemId} -> isTask: ${isTask}`);
            if (isTask) {
                return workItemId;
            }
        } catch (error) {
            console.log(`Warning: Failed to inspect linked work item ${workItemId}: ${error instanceof Error ? error.message : String(error)}`);
        }
    }

    tl.warning(`[ParentResolution] No Task work item found in changeset ${changesetId}.`);
    return undefined;
}

async function resolveParentTaskIdFromShelveset(
    collectionUri: string,
    project: string,
    shelveset: string,
    token: string,
    authType: string
): Promise<number | undefined> {
    tl.warning(`[ParentResolution] Querying work items linked to shelveset: ${shelveset}...`);
    const linkedWorkItemIds = await getTfvcShelvesetLinkedWorkItemIds(
        collectionUri,
        project,
        shelveset,
        token,
        authType
    );

    tl.warning(`[ParentResolution] Shelveset has ${linkedWorkItemIds.length} linked work item(s): [${linkedWorkItemIds.join(', ')}]`);

    for (const workItemId of linkedWorkItemIds) {
        try {
            const isTask = await isTaskWorkItem(collectionUri, project, workItemId, token, authType);
            tl.warning(`[ParentResolution] Shelveset work item ${workItemId} -> isTask: ${isTask}`);
            if (isTask) {
                return workItemId;
            }
        } catch (error) {
            console.log(`Warning: Failed to inspect shelveset-linked work item ${workItemId}: ${error instanceof Error ? error.message : String(error)}`);
        }
    }

    tl.warning(`[ParentResolution] No Task work item found in shelveset.`);
    return undefined;
}

function resolveChangesetAuthor(changeset: any): string | undefined {
    const candidates = [
        typeof changeset?.author === 'string' ? changeset.author : undefined,
        changeset?.author?.uniqueName,
        changeset?.author?.mailAddress,
        changeset?.author?.displayName,
        typeof changeset?.checkedInBy === 'string' ? changeset.checkedInBy : undefined,
        changeset?.checkedInBy?.uniqueName,
        changeset?.checkedInBy?.mailAddress,
        changeset?.checkedInBy?.displayName,
        normalizeInput(tl.getVariable('Build.RequestedForEmail')),
        normalizeInput(tl.getVariable('Build.RequestedFor'))
    ];

    for (const candidate of candidates) {
        const normalized = normalizeInput(typeof candidate === 'string' ? candidate : undefined);
        if (normalized) {
            return normalized;
        }
    }

    return undefined;
}

function resolveShelvesetAuthor(shelveset: any): string | undefined {
    const candidates = [
        typeof shelveset?.owner === 'string' ? shelveset.owner : undefined,
        shelveset?.owner?.uniqueName,
        shelveset?.owner?.mailAddress,
        shelveset?.owner?.displayName,
        shelveset?.ownerName,
        shelveset?.ownerDisplayName,
        shelveset?.createdBy?.uniqueName,
        shelveset?.createdBy?.mailAddress,
        shelveset?.createdBy?.displayName,
        normalizeInput(tl.getVariable('Build.RequestedForEmail')),
        normalizeInput(tl.getVariable('Build.RequestedFor'))
    ];

    for (const candidate of candidates) {
        const normalized = normalizeInput(typeof candidate === 'string' ? candidate : undefined);
        if (normalized) {
            return normalized;
        }
    }

    return undefined;
}

async function createFailureWorkItem(
    collectionUri: string,
    project: string,
    token: string,
    authType: string,
    copilotOutput: string
): Promise<{ id: number; url: string }> {
    const sourceVersion = normalizeInput(tl.getVariable('Build.SourceVersion'));
    const sourceVersionMessage = normalizeInput(tl.getVariable('Build.SourceVersionMessage'));
    const changesetId = resolveTfvcChangesetId();
    const shelveset = resolveTfvcShelveset();

    let changeset: any;
    let shelvesetDetails: any;
    let parentTaskId: number | undefined;

    tl.warning(`[WorkItemContext] Init -> ChangesetId: ${changesetId || 'none'}; Shelveset: ${shelveset || 'none'}; SourceVersion: ${sourceVersion || 'none'}`);

    // For gated builds the shelveset is the actual pending change.
    // Build.SourceVersion points to the last committed changeset on the target branch (unrelated).
    // Therefore, when a shelveset is present we resolve metadata and the parent task from it first,
    // and only fall back to the changeset if the shelveset provides no result.
    if (shelveset) {
        try {
            shelvesetDetails = await getTfvcShelvesetDetails(collectionUri, project, shelveset, token, authType);
        } catch (error) {
            console.log(`Warning: Failed to fetch shelveset metadata for ${shelveset}: ${error instanceof Error ? error.message : String(error)}`);
        }

        try {
            parentTaskId = await resolveParentTaskIdFromShelveset(collectionUri, project, shelveset, token, authType);
        } catch (error) {
            console.log(`Warning: Failed to resolve parent task from shelveset ${shelveset}: ${error instanceof Error ? error.message : String(error)}`);
        }
    }

    if (changesetId) {
        try {
            changeset = await getTfvcChangesetDetails(collectionUri, project, changesetId, token, authType);
        } catch (error) {
            console.log(`Warning: Failed to fetch changeset metadata for ${changesetId}: ${error instanceof Error ? error.message : String(error)}`);
        }

        if (!parentTaskId) {
            try {
                parentTaskId = await resolveParentTaskIdFromChangeset(collectionUri, project, changesetId, token, authType);
            } catch (error) {
                console.log(`Warning: Failed to resolve parent task from changeset ${changesetId}: ${error instanceof Error ? error.message : String(error)}`);
            }
        }
    }

    return new Promise((resolve, reject) => {
        const references = getReviewReferences();
        const sourceVersionForTitle = sourceVersion || 'unknown';
        // Prefer shelveset comment/author: in a gated build the shelveset is the actual
        // pending change, whereas the changeset is an unrelated prior commit on the branch.
        const checkinComment =
            normalizeInput(shelvesetDetails?.comment) ||
            normalizeInput(changeset?.comment) ||
            sourceVersionMessage;
        const title = truncateForTitle(`Code Review - ${checkinComment || sourceVersionForTitle}`);
        const assignedTo = resolveShelvesetAuthor(shelvesetDetails) || resolveChangesetAuthor(changeset);

        tl.warning(`[WorkItemContext] SourceVersion: ${sourceVersionForTitle}; ChangesetId: ${changesetId || 'not resolved'}; Shelveset: ${shelveset || 'not resolved'}`);
        tl.warning(`[WorkItemContext] AssignedTo: ${assignedTo || 'not resolved'}; ParentTaskId: ${parentTaskId || 'not resolved'}; Title: ${title}`);

        if (assignedTo) {
            references.push(`AssignedTo: ${assignedTo}`);
        }
        if (changesetId) {
            references.push(`ChangesetId: ${changesetId}`);
        }
        if (checkinComment) {
            references.push(`CheckinComment: ${checkinComment}`);
        }
        if (shelveset) {
            references.push(`Shelveset: ${shelveset}`);
        }
        if (parentTaskId) {
            references.push(`ParentTaskId: ${parentTaskId}`);
        }

        const detailsHtml = [
            '<h3>Code review findings (blocking)</h3>',
            '<p>The gated code review found blocking issues.</p>',
            '<h4>References</h4>',
            `<ul>${references.map(r => `<li>${escapeHtml(r)}</li>`).join('')}</ul>`,
            '<h4>Copilot output</h4>',
            `<pre>${escapeHtml(copilotOutput.trim() || 'No output generated by Copilot.')}</pre>`
        ].join('');

        const patchOperations: Array<{ op: string; path: string; value: any }> = [
            { op: 'add', path: '/fields/System.Title', value: title },
            { op: 'add', path: '/fields/System.Description', value: detailsHtml }
        ];

        if (assignedTo) {
            patchOperations.push({
                op: 'add',
                path: '/fields/System.AssignedTo',
                value: assignedTo
            });
        }

        if (parentTaskId) {
            patchOperations.push({
                op: 'add',
                path: '/relations/-',
                value: {
                    rel: 'System.LinkTypes.Hierarchy-Reverse',
                    url: `${collectionUri}/_apis/wit/workItems/${parentTaskId}`,
                    attributes: {
                        comment: 'Parent task linked from associated TFVC shelveset or changeset work item.'
                    }
                }
            });
        }

        const patchBody = JSON.stringify(patchOperations);

        const headers: Record<string, string> = {
            'Content-Type': 'application/json-patch+json',
            'Content-Length': Buffer.byteLength(patchBody).toString()
        };

        if (authType === 'Bearer') {
            headers['Authorization'] = `Bearer ${token}`;
        } else {
            const encoded = Buffer.from(`:${token}`).toString('base64');
            headers['Authorization'] = `Basic ${encoded}`;
        }

        const endpoint = `${collectionUri}/${project}/_apis/wit/workitems/$Task?api-version=7.1`;
        const req = https.request(endpoint, { method: 'POST', headers }, (res) => {
            let data = '';
            res.setEncoding('utf8');
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (!res.statusCode || res.statusCode < 200 || res.statusCode >= 300) {
                    reject(new Error(`Create work item failed (${res.statusCode}): ${data}`));
                    return;
                }

                try {
                    const parsed = JSON.parse(data);
                    resolve({
                        id: parsed?.id,
                        url: parsed?.url
                    });
                } catch (error) {
                    reject(new Error(`Failed to parse work item response: ${error instanceof Error ? error.message : String(error)}`));
                }
            });
        });

        req.on('error', (err) => reject(err));
        req.write(patchBody);
        req.end();
    });
}

async function invokeAzureDevOpsApi(url: string, token: string, authType: string): Promise<any> {
    return new Promise((resolve, reject) => {
        const headers: Record<string, string> = {
            'Content-Type': 'application/json'
        };

        if (authType === 'Bearer') {
            headers['Authorization'] = `Bearer ${token}`;
        } else {
            const encoded = Buffer.from(`:${token}`).toString('base64');
            headers['Authorization'] = `Basic ${encoded}`;
        }

        const req = https.request(url, { method: 'GET', headers }, (res) => {
            let data = '';
            res.setEncoding('utf8');
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (!res.statusCode || res.statusCode < 200 || res.statusCode >= 300) {
                    reject(new Error(`Azure DevOps API request failed (${res.statusCode}): ${data}`));
                    return;
                }

                try {
                    resolve(JSON.parse(data));
                } catch (error) {
                    reject(new Error(`Failed to parse Azure DevOps API response: ${error instanceof Error ? error.message : String(error)}`));
                }
            });
        });

        req.on('error', (err) => reject(err));
        req.end();
    });
}

async function getTfvcChangedFiles(
    collectionUri: string,
    project: string,
    sourceVersion: string,
    token: string,
    authType: string
): Promise<string[]> {
    const changesetId = parseTfvcChangesetId(sourceVersion);
    if (!changesetId) {
        return [];
    }

    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/changesets/${changesetId}/changes?api-version=7.1&$top=2000`
            : undefined,
        `${collectionUri}/_apis/tfvc/changesets/${changesetId}/changes?api-version=7.1&$top=2000`
    ].filter((value: string | undefined): value is string => !!value);

    const response = await invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch TFVC changeset ${changesetId}.`
    );

    const items = Array.isArray(response?.value) ? response.value : [];

    return items
        .map((entry: any) => {
            const path = entry?.item?.path;
            const changeType = entry?.changeType || 'edit';
            if (!path) {
                return undefined;
            }
            return `${path} [${changeType}]`;
        })
        .filter((value: string | undefined): value is string => !!value);
}

async function getTfvcShelvesetChangedFiles(
    collectionUri: string,
    project: string,
    shelveset: string,
    token: string,
    authType: string
): Promise<string[]> {
    if (!shelveset) {
        return [];
    }

    const encodedShelveset = encodeURIComponent(shelveset);
    const projectSegment = (project || '').trim().replace(/^\/+|\/+$/g, '');
    const endpointCandidates = [
        projectSegment
            ? `${collectionUri}/${projectSegment}/_apis/tfvc/shelvesets/${encodedShelveset}/changes?api-version=7.1&$top=2000`
            : undefined,
        `${collectionUri}/_apis/tfvc/shelvesets/${encodedShelveset}/changes?api-version=7.1&$top=2000`
    ].filter((value: string | undefined): value is string => !!value);

    const response = await invokeAzureDevOpsApiWithFallback(
        endpointCandidates,
        token,
        authType,
        `Failed to fetch TFVC shelveset ${shelveset}.`
    );

    const items = Array.isArray(response?.value) ? response.value : [];

    return items
        .map((entry: any) => {
            const itemPath = entry?.item?.path;
            const changeType = entry?.changeType || entry?.change?.changeType || 'edit';
            if (!itemPath) {
                return undefined;
            }
            return `${itemPath} [${changeType}]`;
        })
        .filter((value: string | undefined): value is string => !!value);
}

function parseGitChangedFiles(stdout: string, defaultChangeType: string): string[] {
    return (stdout || '')
        .split(/\r?\n/)
        .map(line => line.trim())
        .filter(Boolean)
        .map(line => `${line} [${defaultChangeType}]`);
}

function runGitChangedFilesCommand(workingDirectory: string, args: string[], defaultChangeType: string): string[] {
    const result = child_process.spawnSync('git', args, {
        cwd: workingDirectory,
        encoding: 'utf8',
        shell: true
    });

    if (result.status !== 0 || !result.stdout) {
        return [];
    }

    return parseGitChangedFiles(result.stdout, defaultChangeType);
}

function getGitChangedFiles(workingDirectory: string): string[] {
    try {
        const strategies: Array<{ args: string[]; defaultChangeType: string }> = [
            { args: ['diff', '--name-only', 'HEAD~1', 'HEAD'], defaultChangeType: 'modified' },
            { args: ['show', '--name-only', '--pretty=format:', 'HEAD'], defaultChangeType: 'modified' }
        ];

        for (const strategy of strategies) {
            const files = runGitChangedFilesCommand(workingDirectory, strategy.args, strategy.defaultChangeType);
            if (files.length > 0) {
                return files;
            }
        }

        return [];
    } catch {
        return [];
    }
}

async function prepareGatedReviewContext(
    workingDirectory: string,
    collectionUri: string,
    project: string,
    token: string,
    authType: string
): Promise<void> {
    const provider = (tl.getVariable('Build.Repository.Provider') || '').trim();
    const sourceVersion = (tl.getVariable('Build.SourceVersion') || '').trim();
    const sourceBranch = (tl.getVariable('Build.SourceBranch') || '').trim();
    const buildReason = (tl.getVariable('Build.Reason') || '').trim();
    const shelveset = (tl.getVariable('Build.SourceTfvcShelveset') || '').trim();

    let changedFiles: string[] = [];

    if (provider.toLowerCase() === 'tfsversioncontrol') {
        if (shelveset) {
            try {
                changedFiles = await getTfvcShelvesetChangedFiles(collectionUri, project, shelveset, token, authType);
                if (changedFiles.length > 0) {
                    console.log(`Loaded TFVC changed files from shelveset: ${shelveset}`);
                }
            } catch (error) {
                console.log(`Warning: Failed to fetch TFVC shelveset details: ${error instanceof Error ? error.message : String(error)}`);
            }
        }

        if (changedFiles.length === 0 && sourceVersion) {
            try {
                changedFiles = await getTfvcChangedFiles(collectionUri, project, sourceVersion, token, authType);
            } catch (error) {
                console.log(`Warning: Failed to fetch TFVC changeset details: ${error instanceof Error ? error.message : String(error)}`);
            }
        }
    }

    if (changedFiles.length === 0) {
        changedFiles = getGitChangedFiles(workingDirectory);
    }

    if (changedFiles.length === 0) {
        throw new Error('Unable to identify gated changed files. Aborting review to prevent scanning unrelated repository code.');
    }

    const xmlChangedFiles = filterXmlChangedFiles(changedFiles);
    if (xmlChangedFiles.length === 0) {
        throw new Error('No XML files found in gated changed files. Aborting review because only X++ XML files are in scope.');
    }

    if (xmlChangedFiles.length !== changedFiles.length) {
        console.log(`Filtered gated changed files to XML only: ${xmlChangedFiles.length}/${changedFiles.length} kept.`);
    }

    changedFiles = xmlChangedFiles;

    const prDetailsOutput = path.join(workingDirectory, 'PR_Details.txt');
    const iterationDetailsOutput = path.join(workingDirectory, 'Iteration_Details.txt');

    const details = [
        'GATED BUILD REVIEW CONTEXT (NO PR)',
        `Build.Reason: ${buildReason || '(not available)'}`,
        `Build.Repository.Provider: ${provider || '(not available)'}`,
        `Build.SourceVersion: ${sourceVersion || '(not available)'}`,
        `Build.SourceBranch: ${sourceBranch || '(not available)'}`,
        `Build.SourceTfvcShelveset: ${shelveset || '(not available)'}`,
        '',
        'This run does not have a Pull Request context. Review scope is limited to X++ XML files changed in gated check-in.'
    ].join(os.EOL);

    const changedFilesContent = [
        'GATED CHANGED FILES',
        ...changedFiles.map(file => `- ${file}`)
    ].join(os.EOL);

    fs.writeFileSync(prDetailsOutput, details, 'utf8');
    fs.writeFileSync(iterationDetailsOutput, changedFilesContent, 'utf8');

    console.log(`Gated review context saved to: ${prDetailsOutput}`);
    console.log(`Gated changed files saved to: ${iterationDetailsOutput}`);
}

async function run(): Promise<void> {
    try {
        // Check prerequisites first
        console.log('Checking prerequisites...');
        
        // Check if PowerShell 7 (pwsh) is available
        if (!checkPwshAvailable()) {
            tl.setResult(tl.TaskResult.Failed, 
                'PowerShell 7 (pwsh) is required but not found. ' +
                'Please install PowerShell 7 or later. ' +
                'Visit https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell for installation instructions.');
            return;
        }
        console.log('PowerShell 7 (pwsh) is available.');

        // Check author filter first (before any other processing)
        const authors = tl.getInput('authors');
        if (authors) {
            const requestedForEmail = tl.getVariable('Build.RequestedForEmail') || '';
            const authorList = authors.split(',').map(email => email.trim().toLowerCase());
            const currentAuthor = requestedForEmail.toLowerCase();
            
            console.log('='.repeat(60));
            console.log('Author Filter Check');
            console.log('='.repeat(60));
            console.log(`Configured authors: ${authorList.join(', ')}`);
            console.log(`PR author email: ${requestedForEmail || '(not available)'}`);
            
            if (!authorList.includes(currentAuthor)) {
                console.log(`Result: PR author is NOT in the configured authors list.`);
                console.log('Skipping code review for this PR.');
                console.log('='.repeat(60));
                tl.setResult(tl.TaskResult.Succeeded, 'Skipped: PR author not in configured authors list.');
                return;
            }
            
            console.log(`Result: PR author IS in the configured authors list.`);
            console.log('Proceeding with code review.');
            console.log('='.repeat(60));
        }

        // Get required inputs
        const githubPat = tl.getInputRequired('githubPat');
        
        // Get Azure DevOps authentication settings
        const useSystemAccessToken = tl.getBoolInput('useSystemAccessToken', false);
        const azureDevOpsPat = tl.getInput('azureDevOpsPat');
        
        // Determine which token and auth type to use
        let azureDevOpsToken: string;
        let azureDevOpsAuthType: string;
        
        if (useSystemAccessToken) {
            // Use System.AccessToken (OAuth Bearer token)
            const systemToken = tl.getVariable('System.AccessToken');
            if (!systemToken) {
                tl.setResult(tl.TaskResult.Failed, 
                    'System.AccessToken is not available. Ensure the pipeline has access to the OAuth token. ' +
                    'In YAML pipelines, you may need to explicitly map it using env: SYSTEM_ACCESSTOKEN: $(System.AccessToken)');
                return;
            }
            azureDevOpsToken = systemToken;
            azureDevOpsAuthType = 'Bearer';
            console.log('Using System.AccessToken (OAuth) for Azure DevOps authentication.');
        } else if (azureDevOpsPat) {
            // Use provided PAT (Basic auth)
            azureDevOpsToken = azureDevOpsPat;
            azureDevOpsAuthType = 'Basic';
            console.log('Using Personal Access Token for Azure DevOps authentication.');
        } else {
            tl.setResult(tl.TaskResult.Failed, 
                'Azure DevOps authentication is required. Either provide an Azure DevOps PAT or enable "Use System Access Token".');
            return;
        }
        
        // Get inputs with defaults from pipeline variables
        const organization = normalizeInput(tl.getInput('organization'));
        const collectionUri = normalizeInput(tl.getInput('collectionUri'));
        const project = normalizeInput(tl.getInput('project')) || normalizeInput(tl.getVariable('System.TeamProject'));
        const repository = normalizeInput(tl.getInput('repository')) || normalizeInput(tl.getVariable('Build.Repository.Name'));

        // Resolve the collection URI using priority chain:
        // 1. Explicit collectionUri input
        // 2. organization input -> construct https://dev.azure.com/{org}
        // 3. System.CollectionUri pipeline variable (used directly)
        let resolvedCollectionUri: string | undefined;

        if (collectionUri) {
            resolvedCollectionUri = collectionUri.replace(/\/+$/, '');
            console.log(`Using explicit collection URI: ${resolvedCollectionUri}`);
        } else if (organization) {
            resolvedCollectionUri = `https://dev.azure.com/${organization}`;
            console.log(`Constructed collection URI from organization: ${resolvedCollectionUri}`);
        } else {
            const systemCollectionUri = tl.getVariable('System.CollectionUri');
            if (systemCollectionUri) {
                resolvedCollectionUri = systemCollectionUri.replace(/\/+$/, '');
                console.log(`Auto-detected collection URI from System.CollectionUri: ${resolvedCollectionUri}`);
            }
        }

        if (!resolvedCollectionUri) {
            tl.setResult(tl.TaskResult.Failed,
                'Collection URI could not be determined. Provide collectionUri, organization, or ensure System.CollectionUri is available.');
            return;
        }

        if (!project) {
            tl.setResult(tl.TaskResult.Failed, 'Project is required. Either provide it as an input or ensure System.TeamProject is available.');
            return;
        }

        if (!repository) {
            tl.setResult(tl.TaskResult.Failed, 'Repository is required. Either provide it as an input or ensure Build.Repository.Name is available.');
            return;
        }

        // Get optional inputs
        const timeoutMinutes = parseInt(tl.getInput('timeout') || '15', 10);
        const failOnBlockingFindings = tl.getBoolInput('failOnBlockingFindings', false);
        const model = tl.getInput('model');
        const promptFile = tl.getInput('promptFile');
        const prompt = tl.getInput('prompt');
        const warningPrompt = tl.getInput('warningPrompt');
        const warningPromptFile = tl.getInput('warningPromptFile');
        const blockingPrompt = tl.getInput('blockingPrompt');
        const blockingPromptFile = tl.getInput('blockingPromptFile');
        const promptRaw = tl.getInput('promptRaw');
        const promptFileRaw = tl.getInput('promptFileRaw');

        console.log('='.repeat(60));
        console.log('Copilot Code Review Task');
        console.log('='.repeat(60));
        console.log(`Collection URI: ${resolvedCollectionUri}`);
        console.log(`Project: ${project}`);
        console.log(`Repository: ${repository}`);
        console.log('Mode: VSTS Gated Review (no Pull Request dependency)');
        console.log(`Timeout: ${timeoutMinutes} minutes`);
        console.log(`Fail on blocking findings: ${failOnBlockingFindings ? 'enabled' : 'disabled (report-only mode)'}`);
        if (model) {
            console.log(`Model: ${model}`);
        }
        console.log('='.repeat(60));

        // Set environment variables for PowerShell scripts
        process.env['GH_TOKEN'] = githubPat;
        process.env['AZUREDEVOPS_TOKEN'] = azureDevOpsToken;
        process.env['AZUREDEVOPS_AUTH_TYPE'] = azureDevOpsAuthType;
        process.env['AZUREDEVOPS_COLLECTION_URI'] = resolvedCollectionUri;
        process.env['PROJECT'] = project;
        process.env['REPOSITORY'] = repository;

        const scriptsDir = path.join(__dirname, 'scripts');
        const workingDirectory = tl.getVariable('System.DefaultWorkingDirectory') || process.cwd();

        // Step 1: Install GitHub Copilot CLI if not present
        console.log('\n[Step 1/4] Checking GitHub Copilot CLI installation...');
        const copilotInstalled = await checkCopilotCli();
        if (!copilotInstalled) {
            console.log('GitHub Copilot CLI not found. Installing...');
            await installCopilotCli();
        } else {
            console.log('GitHub Copilot CLI is already installed.');
        }

        console.log('\n[Step 2/4] Preparing gated review context...');
        await prepareGatedReviewContext(
            workingDirectory,
            resolvedCollectionUri,
            project,
            azureDevOpsToken,
            azureDevOpsAuthType
        );
        console.log('\n[Step 3/4] Gated review context ready.');

        // Step 4: Run Copilot CLI for code review
        console.log('\n[Step 4/4] Running Copilot code review...');
        
        // Determine the prompt file to use
        let promptFilePath: string = '';
        let customPromptText: string | null = null;
        let warningPromptText = (warningPrompt || '').trim();
        let blockingPromptText = (blockingPrompt || '').trim();

        // Helper to check if filePath inputs are actually set (filePath inputs return working dir when empty)
        const isPromptFileSet = promptFile &&
            fs.existsSync(promptFile) &&
            fs.statSync(promptFile).isFile();
        const isPromptFileRawSet = promptFileRaw &&
            fs.existsSync(promptFileRaw) &&
            fs.statSync(promptFileRaw).isFile();
        const isWarningPromptFileSet = warningPromptFile &&
            fs.existsSync(warningPromptFile) &&
            fs.statSync(warningPromptFile).isFile();
        const isBlockingPromptFileSet = blockingPromptFile &&
            fs.existsSync(blockingPromptFile) &&
            fs.statSync(blockingPromptFile).isFile();

        if (!warningPromptText && isWarningPromptFileSet) {
            console.log(`Using warning checks prompt from file: ${warningPromptFile}`);
            const warningFileContent = fs.readFileSync(warningPromptFile!, 'utf8').trim();
            if (!warningFileContent) {
                tl.setResult(tl.TaskResult.Failed, `Warning prompt file is empty: ${warningPromptFile}`);
                return;
            }
            if (warningFileContent.includes('"')) {
                tl.setResult(tl.TaskResult.Failed, `Warning prompt cannot include double quotes ("). Please remove them from: ${warningPromptFile}`);
                return;
            }
            warningPromptText = warningFileContent;
        } else if (warningPromptText && isWarningPromptFileSet) {
            console.log('Both warningPrompt and warningPromptFile are set. Using warningPrompt input value.');
        }

        if (!blockingPromptText && isBlockingPromptFileSet) {
            console.log(`Using blocking checks prompt from file: ${blockingPromptFile}`);
            const blockingFileContent = fs.readFileSync(blockingPromptFile!, 'utf8').trim();
            if (!blockingFileContent) {
                tl.setResult(tl.TaskResult.Failed, `Blocking prompt file is empty: ${blockingPromptFile}`);
                return;
            }
            if (blockingFileContent.includes('"')) {
                tl.setResult(tl.TaskResult.Failed, `Blocking prompt cannot include double quotes ("). Please remove them from: ${blockingPromptFile}`);
                return;
            }
            blockingPromptText = blockingFileContent;
        } else if (blockingPromptText && isBlockingPromptFileSet) {
            console.log('Both blockingPrompt and blockingPromptFile are set. Using blockingPrompt input value.');
        }

        const hasRawPromptInput = !!promptRaw || !!isPromptFileRawSet;
        const hasLegacyCustomPrompt = !!prompt || !!isPromptFileSet;
        const hasSplitCustomPrompt = !!warningPromptText || !!blockingPromptText;

        if (promptRaw && isPromptFileRawSet) {
            tl.setResult(tl.TaskResult.Failed,
                'Both promptRaw and promptFileRaw are set. Please use only one raw prompt input.');
            return;
        }

        if (hasRawPromptInput && (hasLegacyCustomPrompt || hasSplitCustomPrompt)) {
            tl.setResult(tl.TaskResult.Failed,
                'Raw prompt inputs (promptRaw/promptFileRaw) cannot be combined with custom prompt inputs. ' +
                'Use either raw prompt mode or template-based custom prompt mode.');
            return;
        }

        if (hasLegacyCustomPrompt && hasSplitCustomPrompt) {
            tl.setResult(tl.TaskResult.Failed,
                'Legacy custom prompt inputs (prompt/promptFile) cannot be combined with warningPrompt/blockingPrompt. ' +
                'Use only one custom prompt mode.');
            return;
        }

        if (promptRaw) {
            // Raw prompt: pass directly to CLI with no modification
            console.log('Using raw prompt from input.');
            promptFilePath = path.join(workingDirectory, '_copilot_prompt.txt');
            fs.writeFileSync(promptFilePath, promptRaw, 'utf8');
            console.log('\nRAW PROMPT:\n' + promptRaw + '\n\n');
        } else if (isPromptFileRawSet) {
            // Raw prompt file: use file contents as-is with no modification
            console.log(`Using raw prompt from file: ${promptFileRaw}`);
            const fileContent = fs.readFileSync(promptFileRaw!, 'utf8');
            if (!fileContent.trim()) {
                tl.setResult(tl.TaskResult.Failed, `Raw prompt file is empty: ${promptFileRaw}`);
                return;
            }
            promptFilePath = path.join(workingDirectory, '_copilot_prompt.txt');
            fs.writeFileSync(promptFilePath, fileContent, 'utf8');
            console.log('\nRAW PROMPT:\n' + fileContent + '\n\n');
        } else if (prompt) {
            // Direct prompt input: merge with template
            console.log('Using custom prompt from input.');
            if (prompt.includes('"')) {
                tl.setResult(tl.TaskResult.Failed, 'Custom prompts cannot include double quotes ("). Please remove any double quotes from your prompt input.');
                return;
            }
            customPromptText = prompt;
        } else if (isPromptFileSet) {
            // Read from prompt file: merge with template
            console.log(`Using custom prompt from file: ${promptFile}`);
            const fileContent = fs.readFileSync(promptFile!, 'utf8').trim();
            if (!fileContent) {
                tl.setResult(tl.TaskResult.Failed, `Prompt file is empty: ${promptFile}`);
                return;
            }
            if (fileContent.includes('"')) {
                tl.setResult(tl.TaskResult.Failed, `Custom prompts cannot include double quotes ("). Please remove any double quotes from the prompt file: ${promptFile}`);
                return;
            }
            customPromptText = fileContent;
        }

        if (customPromptText || hasSplitCustomPrompt) {
            // Use custom prompt template with placeholder replacement
            const customPromptTemplate = path.join(scriptsDir, 'prompt-custom.txt');
            const templateContent = fs.readFileSync(customPromptTemplate, 'utf8');
            const mergedPrompt = templateContent
                .replace('%CUSTOMPROMPT%', customPromptText || 'No additional generic instructions provided.')
                .replace('%WARNING_PROMPT%', warningPromptText || 'No additional warning-only checks provided.')
                .replace('%BLOCKING_PROMPT%', blockingPromptText || 'No additional blocking checks provided.');
            console.log('\nCUSTOM PROMPT:\n' + mergedPrompt + '\n\n');

            // Write merged prompt to a temp file in the working directory
            promptFilePath = path.join(workingDirectory, '_copilot_prompt.txt');
            fs.writeFileSync(promptFilePath, mergedPrompt, 'utf8');
            console.log('Custom prompt instructions merged with template.');
        } else if (!promptRaw && !isPromptFileRawSet) {
            const gatedPrompt = [
                'You are reviewing a VSTS/Azure DevOps gated check-in run that has no Pull Request context.',
                'Read PR_Details.txt and Iteration_Details.txt for build and changed-files context.',
                'Review ONLY the files listed under "GATED CHANGED FILES" in Iteration_Details.txt.',
                'Those files are in scope ONLY when they are X++ XML files (*.xml).',
                'Ignore and do not comment on any non-XML file type.',
                'Do not inspect, infer, or comment on any file that is not explicitly listed there.',
                'If a finding would require analyzing non-listed files, skip that finding and continue.',
                'If no listed files are present or readable, output a rejected result explaining that scope could not be validated.',
                'Do not generate or call PR comment scripts. This mode is for gated check-ins only.',
                'Return only one markdown block starting exactly with: ## Code Review — Findings',
                'Include only: file reviewed, result (ACCEPTED/REJECTED), issues (if any), and final summary.',
                'Do not include any introduction, process notes, tool logs, or extra sections before/after the findings block.'
            ].join(os.EOL + os.EOL);
            promptFilePath = path.join(workingDirectory, '_copilot_prompt.txt');
            fs.writeFileSync(promptFilePath, gatedPrompt, 'utf8');
            console.log('Using gated check-in prompt (no PR comments).');
        }
        
        // Run Copilot CLI with timeout
        const timeoutMs = timeoutMinutes * 60 * 1000;
        const copilotOutput = await runCopilotCli(promptFilePath, model, workingDirectory, timeoutMs);

        const normalizedReviewOutput = extractReviewFindings(copilotOutput);
        const reviewReportPath = path.join(workingDirectory, 'Review_Recommendations.md');
        const report = [
            '# D365FO Gated Review Recommendations',
            '',
            `- Generated: ${new Date().toISOString()}`,
            `- Project: ${project}`,
            `- Repository: ${repository}`,
            '',
            '## Copilot Review Output',
            '',
            '```text',
            normalizedReviewOutput,
            '```'
        ].join(os.EOL);
        fs.writeFileSync(reviewReportPath, report, 'utf8');
        console.log(`Review recommendations saved to: ${reviewReportPath}`);
        tl.uploadSummary(reviewReportPath);

        if (hasBlockingFindings(normalizedReviewOutput)) {
            if (!failOnBlockingFindings) {
                try {
                    const workItem = await createFailureWorkItem(
                        resolvedCollectionUri,
                        project,
                        azureDevOpsToken,
                        azureDevOpsAuthType,
                        normalizedReviewOutput
                    );

                    const reportOnlyMessage = workItem?.id
                        ? `Blocking findings detected (report-only mode). Work item created: ${workItem.id}`
                        : 'Blocking findings detected (report-only mode). Work item created.';

                    console.log(reportOnlyMessage);
                    if (workItem?.url) {
                        console.log(`Work item URL: ${workItem.url}`);
                    }

                    tl.setResult(tl.TaskResult.Succeeded, reportOnlyMessage);
                    return;
                } catch (workItemError) {
                    const createError = workItemError instanceof Error ? workItemError.message : String(workItemError);
                    const reportOnlyMessage =
                        'Blocking findings detected (report-only mode), but failed to create Azure DevOps Task work item: ' +
                        createError;
                    tl.warning(reportOnlyMessage);
                    tl.setResult(tl.TaskResult.Succeeded, reportOnlyMessage);
                    return;
                }
            }

            try {
                const workItem = await createFailureWorkItem(
                    resolvedCollectionUri,
                    project,
                    azureDevOpsToken,
                    azureDevOpsAuthType,
                    normalizedReviewOutput
                );

                const workItemMessage = workItem?.id
                    ? `Blocking findings detected. Work item created: ${workItem.id}`
                    : 'Blocking findings detected. Work item created.';

                console.log(workItemMessage);
                if (workItem?.url) {
                    console.log(`Work item URL: ${workItem.url}`);
                }

                tl.setResult(tl.TaskResult.Failed, workItemMessage);
                return;
            } catch (workItemError) {
                const createError = workItemError instanceof Error ? workItemError.message : String(workItemError);
                tl.setResult(
                    tl.TaskResult.Failed,
                    `Blocking findings detected, but failed to create Azure DevOps Task work item: ${createError}`
                );
                return;
            }
        }

        console.log('\n' + '='.repeat(60));
        console.log('Copilot Code Review completed successfully!');
        console.log('='.repeat(60));

        tl.setResult(tl.TaskResult.Succeeded, 'Copilot code review completed.');
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        tl.setResult(tl.TaskResult.Failed, `Task failed: ${errorMessage}`);
    }
}

async function checkCopilotCli(): Promise<boolean> {
    try {
        const result = child_process.spawnSync('copilot', ['--version'], {
            encoding: 'utf8',
            shell: true
        });
        return result.status === 0;
    } catch {
        return false;
    }
}

async function installCopilotCli(): Promise<void> {
    return new Promise((resolve, reject) => {
        let command: string;
        let args: string[];

        if (isWindows()) {
            console.log('Installing GitHub Copilot CLI via winget...');
            command = 'winget';
            args = ['install', 'GitHub.Copilot', '--silent', '--accept-package-agreements', '--accept-source-agreements'];
        } else {
            console.log('Installing GitHub Copilot CLI via official install script...');
            // Use the official GitHub install script which downloads a pre-built binary
            // The script installs to $HOME/.local/bin by default for non-root users
            // Pass the full command as a single string when using shell: true
            command = 'curl -fsSL https://gh.io/copilot-install | bash';
            args = [];
        }
        
        const installProcess = child_process.spawn(
            command,
            args,
            {
                shell: true,
                stdio: 'inherit'
            }
        );

        installProcess.on('close', (code: number | null) => {
            if (code === 0) {
                console.log('GitHub Copilot CLI installed successfully.');
                // On Linux, add the install location to PATH for the current process
                if (!isWindows()) {
                    const homeDir = process.env['HOME'] || '';
                    const localBin = path.join(homeDir, '.local', 'bin');
                    process.env['PATH'] = `${localBin}:${process.env['PATH']}`;
                    console.log(`Added ${localBin} to PATH.`);
                }
                resolve();
            } else {
                reject(new Error(`Failed to install GitHub Copilot CLI. Exit code: ${code}`));
            }
        });

        installProcess.on('error', (err: Error) => {
            reject(new Error(`Failed to install GitHub Copilot CLI: ${err.message}`));
        });
    });
}

async function runCopilotCli(promptFilePath: string, model: string | undefined, workingDirectory: string, timeoutMs: number): Promise<string> {
    return new Promise((resolve, reject) => {
        // Build PowerShell command that reads the generated prompt file and passes content to Copilot CLI.
        let copilotCmd = `copilot -p "$prompt" --allow-all-paths --allow-all-tools --deny-tool 'shell(git push)'`;
        if (model) {
            copilotCmd += ` --model ${model}`;
        }
        
        const printPrompt = `Write-Host ========== START PROMPT ==========; Write-Host $prompt; Write-Host ========== END PROMPT ==========;`;
        const envRefresh = `$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User");`
        const psCommand = `${envRefresh} $prompt = Get-Content -Path '${promptFilePath}' -Raw; ${printPrompt} ${copilotCmd}`;
        console.log(`Running Powershell: ${psCommand}`);
        
        const envVars = { ...process.env };
        let combinedOutput = '';
        
        const copilotProcess = child_process.spawn(
            'pwsh',
            ['-NoProfile', '-Command', psCommand],
            {
                shell: false,
                stdio: ['ignore', 'pipe', 'pipe'],
                cwd: workingDirectory,
                env: envVars
            }
        );

        copilotProcess.stdout.on('data', (chunk: Buffer) => {
            const text = chunk.toString();
            combinedOutput += text;
            process.stdout.write(text);
        });

        copilotProcess.stderr.on('data', (chunk: Buffer) => {
            const text = chunk.toString();
            combinedOutput += text;
            process.stderr.write(text);
        });

        // Set up timeout
        const timeoutId = setTimeout(() => {
            console.log(`\nTimeout reached (${timeoutMs / 60000} minutes). Terminating Copilot process...`);
            copilotProcess.kill('SIGTERM');
            reject(new Error(`Copilot review timed out after ${timeoutMs / 60000} minutes`));
        }, timeoutMs);

        copilotProcess.on('close', (code) => {
            clearTimeout(timeoutId);
            if (code === 0) {
                resolve(combinedOutput);
            } else {
                reject(new Error(`Copilot CLI exited with code: ${code}`));
            }
        });

        copilotProcess.on('error', (err) => {
            clearTimeout(timeoutId);
            reject(new Error(`Failed to run Copilot CLI: ${err.message}`));
        });
    });
}

run();
